import { z } from 'zod';
import { normalize } from '../../shared/core.js';
const text=(max)=>z.string().trim().min(1).max(max);
const evidence=z.string().uuid().nullable().default(null);
export const schemas={
 sample:z.object({title:text(160),sample_code:text(50).min(3).regex(/^[A-Za-z0-9][A-Za-z0-9_-]+$/),jar_code:text(50).regex(/^[A-Za-z0-9_-]+$/),lot_code:text(50),origin:text(500),process_notes:z.string().trim().max(1500).default(''),production_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().startsWith(v)).nullable().default(null),evidence_id:evidence,published:z.boolean().default(false)}).strict(),
 rubric:z.object({title:text(160),criteria:z.array(z.object({label:text(100),weight:z.number().int().min(1).max(100)}).strict()).min(1).max(10).refine(rows=>rows.reduce((n,r)=>n+r.weight,0)===100,'Tổng trọng số phải bằng 100.').refine(rows=>new Set(rows.map(r=>r.label)).size===rows.length,'Tên tiêu chí không được trùng.'),evidence_id:evidence,published:z.literal(false).default(false)}).strict(),
 clause:z.object({title:text(160),standard_code:text(100),clause:text(100),edition:text(40),citation:text(500),source_url:z.url().refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}),excerpt:text(4000),limitation:text(1000),rights_confirmed:z.literal(true),evidence_id:evidence,published:z.boolean().default(false)}).strict()
};
export function weightedScore(values,criteria){if(!Array.isArray(values)||values.length!==criteria.length||values.some(v=>typeof v!=='number'||!Number.isFinite(v)||v<0||v>10))return null;return Math.round(values.reduce((n,v,i)=>n+v*criteria[i].weight/10,0)*100)/100;}
export function rankClauses(query,records){const tokens=[...new Set(normalize(query).split(' ').filter(x=>x.length>1))];return records.map(row=>{const d=row.data;const s=normalize([d.title,d.standard_code,d.clause,d.excerpt].join(' '));return{...row,match_count:tokens.filter(t=>s.includes(t)).length};}).filter(r=>r.match_count).sort((a,b)=>b.match_count-a.match_count).slice(0,5);}
export function sentimentSummary(comments){const counts={positive:0,negative:0,mixed:0,unclear:0};for(const comment of comments){const text=' '+normalize(comment)+' ';const has=words=>words.some(w=>text.includes(' '+w+' '));const bad=has(['khong thich','qua man','qua nhat','dang','kho chiu','khong ngon']);const good=has(['thom','ngon','hai long','thich','vua mieng'])&&!has(['khong ngon','khong thich']);counts[bad&&good?'mixed':bad?'negative':good?'positive':'unclear']++;}return{mode:'keyword_rules',count:comments.length,counts,confidence:null,notice:'Phân loại từ khóa tham khảo; cần đối chiếu nhận xét gốc. Không thay thế đánh giá cảm quan.'};}
