import { operation } from '../db/operation.mjs';
import { Router } from 'express';
import { randomUUID,randomBytes } from 'node:crypto';
import QRCode from 'qrcode';
import { schemas,weightedScore,rankClauses,sentimentSummary } from '../services/research-model.mjs';
import { rateLimit } from '../security/rate-limit.mjs';
import {atlasDiagnostic} from '../services/integration-diagnostics.mjs';
const decode=row=>row?{id:row.id,kind:row.kind,title:row.title,data:JSON.parse(row.data_json),published:!!row.published,public_token:row.public_token,revision:row.revision,created_at:row.created_at,updated_at:row.updated_at}:null;
export function researchRouter(db,security,config){
 const r=Router(),get=async id=>decode(await operation(db,'research.get',()=>db.prepare('SELECT * FROM research_records WHERE id=?')).get(id));
 const list=async kind=>(await operation(db,'research.list',()=>db.prepare('SELECT * FROM research_records WHERE kind=? ORDER BY id LIMIT 500')).all(kind)).map(decode);
 const evidenceExists=async id=>!id||!!await operation(db,'documents.get',()=>db.prepare('SELECT id FROM quality_documents WHERE id=?')).get(id);
 r.get('/research/clauses',rateLimit(30,'search_rate_limit'),async(req,res)=>{const q=req.query.q??'';if(typeof q!=='string'||q.length>200)return res.status(400).json({error:'invalid_query'});const rows=(await list('clause')).filter(x=>x.published);const items=q.trim()?rankClauses(q,rows):rows.slice(0,25);res.json({mode:'lexical',items:items.map(({public_token,...x})=>x),total_published:rows.length,notice:rows.length?'Đối chiếu đúng phiên bản, điều khoản và giới hạn của nguồn.':'Chưa có điều khoản TCVN được cung cấp và công bố.'});});
 const trace=async(req,res,next)=>{if(!/^[a-f0-9]{32}$/.test(req.params.token))return res.status(404).json({error:'sample_not_found'});const item=decode(await operation(db,'research.trace',()=>db.prepare("SELECT * FROM research_records WHERE public_token=? AND kind='sample' AND published=1")).get(req.params.token));if(!item)return res.status(404).json({error:'sample_not_published'});req.trace=item;next();};
 r.get('/trace/:token',trace,(req,res)=>{const {evidence_id,...data}=req.trace.data;res.json({id:req.trace.id,revision:req.trace.revision,data,updated_at:req.trace.updated_at,evidence_status:evidence_id?'Hồ sơ đã được người vận hành đính kèm; chưa xác thực độc lập.':'Chưa có minh chứng đính kèm.',notice:'Thông tin truy xuất do dự án cung cấp; QR không phải chứng nhận chất lượng.'});});
 r.get('/trace/:token/qr.svg',trace,async(req,res)=>{const origin=config.publicOrigin||`http://127.0.0.1:${config.port}`;const svg=await QRCode.toString(`${origin}/truy-xuat.html?sample=${req.params.token}`,{type:'svg',margin:4,errorCorrectionLevel:'Q'});res.type('image/svg+xml').send(svg);});
 r.use('/admin/research',security.requireAdmin);
 r.post('/admin/research/diagnostics/atlas',rateLimit(2,'diagnostic_rate_limit'),async(req,res)=>res.json(await atlasDiagnostic(config)));
 r.get('/admin/research/:kind',async(req,res)=>{if(!Object.hasOwn(schemas,req.params.kind))return res.status(404).json({error:'unknown_kind'});res.json({items:await list(req.params.kind),limit:500});});
 const save=async(req,res)=>{const kind=req.params.kind,schema=schemas[kind];if(!Object.hasOwn(schemas,kind))return res.status(404).json({error:'unknown_kind'});const parsed=schema.safeParse(req.body?.data);if(!parsed.success)return res.status(422).json({error:'invalid_record',errors:Object.fromEntries(parsed.error.issues.map(i=>[i.path.join('.'),i.message]))});const data=parsed.data;if(!await evidenceExists(data.evidence_id))return res.status(422).json({error:'evidence_not_found'});const stamp=new Date().toISOString();
  if(req.params.id){const old=await get(req.params.id);if(!old||old.kind!==kind)return res.status(404).json({error:'record_not_found'});if(!Number.isInteger(req.body.revision)||old.revision!==req.body.revision)return res.status(409).json({error:'revision_conflict'});if(kind==='rubric')return res.status(409).json({error:'rubric_immutable_create_new_version'});
   const result=await operation(db,'research.update',()=>db.prepare('UPDATE research_records SET identity_key=?,title=?,data_json=?,published=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?')).run(kind==='sample'?data.sample_code+'|'+data.jar_code:null,data.title,JSON.stringify(data),Number(data.published),stamp,old.id,old.revision);if(!result.changes)return res.status(409).json({error:'revision_conflict'});await security.audit(req.principal.account_id,'RESEARCH_UPDATE',old.id);return res.json(await get(old.id));}
  const id=randomUUID();await operation(db,'research.insert',()=>db.prepare('INSERT INTO research_records(id,kind,identity_key,title,data_json,published,public_token,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)')).run(id,kind,kind==='sample'?data.sample_code+'|'+data.jar_code:null,data.title,JSON.stringify(data),Number(data.published),randomBytes(16).toString('hex'),stamp,stamp);await security.audit(req.principal.account_id,'RESEARCH_CREATE',id);res.status(201).json(await get(id));
 };
 const checkedSave=async(req,res,next)=>{try{await save(req,res);}catch(e){if(e.code===11000||e.code==='23505'||(e.code==='ERR_SQLITE_ERROR'&&String(e.message).includes('UNIQUE constraint')))return res.status(409).json({error:'duplicate_sample_jar'});next(e);}};r.post('/admin/research/:kind',checkedSave);r.put('/admin/research/:kind/:id',checkedSave);
 r.use('/judge/research',security.requireReviewer);
 r.get('/judge/research/setup',async(req,res)=>res.json({samples:await list('sample'),rubrics:await list('rubric'),evidence_documents:req.principal.role==='ADMIN'?await operation(db,'documents.evidence',()=>db.prepare('SELECT id,title,doc_type,evidence_status FROM quality_documents ORDER BY created_at DESC,id LIMIT 500')).all():[],evidence_limit:500,rubric_status:'DRAFT',notice:'Tiêu chí do dự án nhập; chưa xác nhận là thể lệ chấm thi chính thức.'}));
 r.get('/judge/research/scores',async(req,res)=>{const rows=await operation(db,'scores.summary',()=>db.prepare(`SELECT s.rubric_id,s.sample_id,r.revision AS current_sample_revision,count(*) AS judges,avg(s.total) AS mean_total,
  sum(CASE WHEN s.sample_revision=r.revision THEN 1 ELSE 0 END) AS current_judges,
  sum(CASE WHEN s.sample_revision<>r.revision THEN 1 ELSE 0 END) AS stale_judges,
  avg(CASE WHEN s.sample_revision=r.revision THEN s.total ELSE NULL END) AS current_mean_total
  FROM research_scores s JOIN research_records r ON r.id=s.sample_id GROUP BY s.rubric_id,s.sample_id,r.revision ORDER BY s.sample_id,s.rubric_id`)).all();const mine=await operation(db,'scores.mine',()=>db.prepare('SELECT rubric_id,sample_id,scores_json,total,revision,sample_revision FROM research_scores WHERE judge_id=?')).all(req.principal.account_id||'');res.json({items:rows,mine:mine.map(({scores_json,...x})=>({...x,scores:JSON.parse(scores_json)})),scale:'0–100',status:'Điểm nội bộ theo bộ tiêu chí dự án, chưa phải kết quả FID chính thức.'});});
 r.post('/judge/research/scores',async(req,res)=>{if(!req.principal.account_id)return res.status(403).json({error:'judge_session_required'});const {rubric_id,sample_id,scores,sample_revision,revision=0}=req.body||{};if(typeof rubric_id!=='string'||typeof sample_id!=='string'||!Number.isInteger(revision)||revision<0||!Number.isInteger(sample_revision)||sample_revision<1)return res.status(422).json({error:'invalid_score'});const rubric=await get(rubric_id),sample=await get(sample_id);if(rubric?.kind!=='rubric'||sample?.kind!=='sample')return res.status(404).json({error:'record_not_found'});if(sample_revision!==sample.revision)return res.status(409).json({error:'sample_revision_conflict'});const total=weightedScore(scores,rubric.data.criteria);if(total===null)return res.status(422).json({error:'scores_must_match_criteria_and_range_0_10'});let result;
  try {
  if(revision===0)result=await operation(db,'scores.insert',()=>db.prepare('INSERT INTO research_scores(rubric_id,sample_id,judge_id,scores_json,total,revision,sample_revision,updated_at) VALUES(?,?,?,?,?,1,?,?) ON CONFLICT(rubric_id,sample_id,judge_id) DO NOTHING')).run(rubric_id,sample_id,req.principal.account_id,JSON.stringify(scores),total,sample.revision,new Date().toISOString());
  else result=await operation(db,'scores.update',()=>db.prepare('UPDATE research_scores SET scores_json=?,total=?,revision=revision+1,sample_revision=?,updated_at=? WHERE rubric_id=? AND sample_id=? AND judge_id=? AND revision=?')).run(JSON.stringify(scores),total,sample.revision,new Date().toISOString(),rubric_id,sample_id,req.principal.account_id,revision);
  } catch(e) {if(e.constraint==='research_score_sample_revision'||(e.code==='ERR_SQLITE_ERROR'&&String(e.message).includes('research_score_sample_revision')))return res.status(409).json({error:'sample_revision_conflict'});throw e;}
  if(!result.changes)return res.status(409).json({error:'revision_conflict'});await security.audit(req.principal.account_id,'RESEARCH_SCORE',sample_id);res.json({total,revision:revision+1,sample_revision:sample.revision});
 });
 r.get('/judge/research/sentiment',async(req,res)=>{const {session_code,sample_code}=req.query;if(typeof session_code!=='string'||typeof sample_code!=='string'||session_code.length>50||sample_code.length>50)return res.status(400).json({error:'sample_and_session_required'});const rows=await operation(db,'sensory.comments',()=>db.prepare("SELECT comments FROM sensory_evaluations WHERE session_code=? AND sample_code=? AND comments<>'' ORDER BY created_at DESC LIMIT 1000")).all(session_code,sample_code);res.json({...sentimentSummary(rows.map(x=>x.comments)),limit:1000});});
 return r;
}
