import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,createHash } from 'node:crypto';
import { openMongoDatabase } from '../backend/db/mongodb.mjs';
import { createApp } from '../backend/app.mjs';
import { loadConfig } from '../backend/config.mjs';
import { createAccount,rotateJudgeAccessCode,bootstrapAccessAccounts } from '../backend/security/auth.mjs';
import { documentStorage } from '../backend/services/document-storage.mjs';
import { dataJobs,projectDocument } from '../backend/services/data-projections.mjs';
import { syncData } from '../backend/services/data-sync.mjs';
import { decisionReviews } from '../backend/repositories/decision-reviews.mjs';
import {openMongoStore} from '../backend/services/mongo-store.mjs';
import {createAtlasLabeling} from '../backend/services/atlas-labeling.mjs';
import {createKnowledgeBatch} from '../backend/services/knowledge-batch.mjs';

test('Atlas primary: persistence, concurrent submissions, judge access, revisions, JSON outbox and private GridFS', {skip:process.env.RUN_ATLAS_TESTS!=='true',timeout:180000}, async()=>{
  const name='musuroom_verify_'+randomUUID().replaceAll('-','').slice(0,16);
  const config=loadConfig({MONGO_ENABLED:'true',MONGODB_URI:process.env.MONGODB_URI,MONGODB_DATABASE:name,DATABASE_PROVIDER:'mongodb',STORAGE_PROVIDER:'mongodb',API_WRITE_TOKEN:'test-only-token-with-at-least-32-characters'});
  let db=await openMongoDatabase(config),server;
  try {
    const admin=await createAccount(db,{name:'Atlas test admin',role:'ADMIN'});
    const judge=await createAccount(db,{name:'Atlas test judge'});
    server=createApp({config,database:db});await new Promise(r=>server.listen(0,'127.0.0.1',r));
    const base=`http://127.0.0.1:${server.address().port}`;
    const call=(path,method='GET',body,session)=>fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});
    const login=async account=>{const r=await call('/api/v1/judge/verify','POST',{access_code:account.access_code});assert.equal(r.status,200);return{cookie:r.headers.get('set-cookie').split(';')[0],csrf:(await r.json()).csrf_token};};
    const a=await login(admin),j=await login(judge);
    assert.equal((await(await call('/healthz')).json()).database_provider,'mongodb');
    assert.equal((await(await call('/api/knowledge')).json()).total,6);
    assert.equal((await call('/api/v1/admin/leads')).status,401);
    assert.equal((await call('/api/v1/admin/leads','GET',null,j)).status,403);
    const survey={session_code:'TEST-ATLAS',sample_code:'NAM-01',tester_type:'CONSUMER',submission_key:randomUUID(),color_score:7,aroma_score:7,umami_taste_score:7,aftertaste_score:7,overall_acceptance:7,comments:'Thơm ngon'};
    const responses=await Promise.all([call('/api/v1/sensory/submit','POST',survey),call('/api/v1/sensory/submit','POST',survey)]);
    assert.deepEqual(responses.map(r=>r.status).sort(),[200,201]);
    assert.equal((await call('/api/v1/sensory/submit','POST',{...survey,color_score:8})).status,409);
    for(const score of [3,5])assert.equal((await call('/api/v1/sensory/submit','POST',{...survey,submission_key:randomUUID(),color_score:score})).status,201);
    const analytics=await(await call('/api/v1/sensory/analytics?session_code=TEST-ATLAS&sample_code=NAM-01','GET',null,j)).json();
    assert.equal(analytics.count,3);assert.equal(analytics.metrics.color_score.mean,5);assert.equal(analytics.metrics.color_score.sd,2);
    const lead={full_name:'Atlas Fixture',phone_or_email:'atlas@example.invalid',organization_type:'INDIVIDUAL',consent:true};
    const registered=await Promise.all([call('/api/v1/leads/register','POST',lead),call('/api/v1/leads/register','POST',lead)]);
    assert.deepEqual(registered.map(r=>r.status).sort(),[200,201]);
    const leads=await(await call('/api/v1/admin/leads','GET',null,a)).json();assert.equal(leads.items.length,1);
    assert.equal((await call('/api/v1/admin/leads/'+leads.items[0].id,'PATCH',{status:'SENT'},a)).status,200);
    const sample={title:'Atlas sample',sample_code:'NAM-01',jar_code:'HU-01',lot_code:'LO-01',origin:'Test only',published:true};
    let r=await call('/api/v1/admin/research/sample','POST',{data:sample},a);assert.equal(r.status,201);const row=await r.json();
    assert.equal((await call('/api/v1/admin/research/sample','POST',{data:sample},a)).status,409);
    const rubric=await(await call('/api/v1/admin/research/rubric','POST',{data:{title:'Fixture criteria',criteria:[{label:'Taste',weight:70},{label:'Method',weight:30}]}},a)).json();
    const score={rubric_id:rubric.id,sample_id:row.id,sample_revision:1,scores:[8,6],revision:0};
    assert.equal((await call('/api/v1/judge/research/scores','POST',score,j)).status,200);
    assert.equal((await call('/api/v1/judge/research/scores','POST',score,j)).status,409);
    assert.equal((await(await call('/api/v1/judge/research/scores','GET',null,j)).json()).items[0].current_mean_total,74);
    r=await call('/api/v1/admin/research/sample/'+row.id,'PUT',{data:{...sample,origin:'Changed source'},revision:1},a);assert.equal(r.status,200);
    assert.equal((await call('/api/v1/judge/research/scores','POST',{...score,revision:1},j)).status,409);
    const summary=await(await call('/api/v1/judge/research/scores','GET',null,j)).json();assert.equal(summary.items[0].stale_judges,1);assert.equal(summary.items[0].current_mean_total,null);
    assert.equal((await call('/api/v1/trace/'+row.public_token)).status,200);
    const clause={title:'Test clause',standard_code:'TEST',clause:'1',edition:'2026',citation:'Fixture only',source_url:'https://example.com/reference',excerpt:'Mushroom research fixture.',limitation:'Not a real standard',rights_confirmed:true,published:true};
    const clauseRow=await(await call('/api/v1/admin/research/clause','POST',{data:clause},a)).json();
    const embedding=Array(384).fill(0);embedding[0]=1;
    assert.equal((await call('/api/v1/admin/vectors/import','POST',{record_id:clauseRow.id,source_revision:1,model:'fixture',embedding},a)).status,200);
    const vectors=await(await call('/api/v1/admin/vectors/search','POST',{model:'fixture',embedding},a)).json();assert.equal(vectors.items[0].id,clauseRow.id);assert.equal(vectors.items[0].similarity,1);
    await assert.rejects(db.collection('sensory_evaluations').insertOne({id:randomUUID(),color_score:99}),e=>e.code===121);
    const bytes=Buffer.from('Private evidence fixture');const id=randomUUID(),filename=id+'.txt';
    await documentStorage(config,undefined,db).write(filename,bytes,'text/plain');
    await db.operation('documents.insert').run(id,'Test report','REPORT',filename,'text/plain',bytes.length,createHash('sha256').update(bytes).digest('hex'),'FINAL');
    assert.equal((await call('/api/v1/judge/documents/'+id)).status,401);
    assert.equal(await(await call('/api/v1/judge/documents/'+id,'GET',null,j)).text(),bytes.toString());
    const measured={sample_code:'MEASURED-01',label:'Measured fixture',origin:'Fixture',measured_at:'2026-10-07',evidence_document_id:id,metrics:{moisture_percent:4},nutrition:{},publication_status:'PUBLIC'};
    assert.equal((await call('/api/v1/admin/product-samples','POST',measured,a)).status,201);
    assert.equal((await call('/api/v1/admin/product-samples','POST',measured,a)).status,409);
    const products=await(await call('/api/v1/product/batches')).json();assert.equal(products.items[0].metrics.moisture_percent,4);
    assert.equal((await call('/api/v1/sensory/export','POST',{session_code:'TEST-ATLAS',sample_code:'NAM-01'},j)).status,200);
    const jobs=await dataJobs(db,{limit:100});assert.equal(jobs.length,8);
    const doc=await projectDocument(db,jobs.find(x=>x.resource_type==='knowledge'),config.mongoSource);
    const reviews=decisionReviews(db),version=await reviews.save(doc,{mode:'local',requires_review:true});
    assert.equal((await reviews.list(' ',25,'pending')).length,1);assert.equal(await reviews.review(doc.resource_id,version,'confirmed'),true);
    const records=[];assert.equal((await syncData({db,config,store:{write:async rows=>records.push(...rows)}})).synced,8);
    const aggregate=records.find(x=>x.type==='sensory');assert.equal(aggregate.data.count,3);assert.ok(!JSON.stringify(aggregate).includes(survey.comments));
    await rotateJudgeAccessCode(db,judge.account_id,'fixture-rotated-secret!');
    assert.equal((await call('/api/v1/auth/session','GET',null,j)).status,401);
    const boot={...config,judgeBootstrapCode:'fixture-bootstrap-secret!'};
    await bootstrapAccessAccounts(db,boot);const first=await db.operation('accounts.get').get('11111111-1111-4111-8111-111111111111');
    await bootstrapAccessAccounts(db,boot);const second=await db.operation('accounts.get').get(first.id);assert.equal(first.secret_hash,second.secret_hash);assert.equal(first.expires_at,second.expires_at);
    await new Promise(resolve=>server.close(resolve));await server.databaseClosed;server=null;
    db=await openMongoDatabase(config);
    assert.equal((await db.operation('sensory.list').all('TEST-ATLAS','NAM-01')).length,3);
    assert.equal((await db.operation('leads.get').get(leads.items[0].id)).status,'SENT');
    assert.deepEqual(await documentStorage(config,undefined,db).read(filename),bytes);
  } finally {
    if(server){await new Promise(resolve=>server.close(resolve));await server.databaseClosed;db=await openMongoDatabase(config);}
    // This database was generated by this test, never a user-selected database.
    if(db.database.databaseName!==name||!/^musuroom_verify_[a-f0-9]{16}$/.test(name))throw new Error('Invalid cleanup target');
    await db.database.dropDatabase();await db.close();
  }
});

test('Atlas label jobs: leases, checkpoints, blocked Jev, stale sources, cancellation, schema and audit privacy', {skip:process.env.RUN_ATLAS_TESTS!=='true',timeout:180000},async()=>{
 const name='musuroom_verify_'+randomUUID().replaceAll('-','').slice(0,16);
 const config=loadConfig({MONGO_ENABLED:'true',MONGODB_URI:process.env.MONGODB_URI,MONGODB_DATABASE:name,DATABASE_PROVIDER:'mongodb',STORAGE_PROVIDER:'mongodb'});
 const db=await openMongoDatabase(config);let mirror;
 try{
  mirror=await openMongoStore(config);await syncData({db,config,store:mirror});
  const labeler=createAtlasLabeling(db,config);
  const plan=await labeler.preview({limit:6,allow_remote:false});assert.equal(plan.eligible,6);assert.equal(plan.request_preview.articles.length,5);assert.equal(plan.batch_size,5);
  const first=await labeler.enqueue({limit:6,allow_remote:false});
  await assert.rejects(labeler.enqueue({limit:6,allow_remote:false}),error=>error.code==='label_run_active');
  const attempts=await Promise.all([labeler.runOnce(),labeler.runOnce()]);assert.equal(attempts.filter(result=>result.mode==='processed').length,1);
  let run=await labeler.get(first.id);assert.equal(run.scanned,5);assert.equal(run.status,'queued');
  await db.collection('label_runs').updateOne({id:first.id},{$set:{status:'running',lock_owner:'expired-fixture',lease_until:0}});
  assert.equal((await labeler.runOnce()).mode,'processed');run=await labeler.get(first.id);assert.equal(run.status,'completed');assert.equal(run.scanned,6);assert.equal(run.local,6);assert.equal(run.jev,0);
  assert.equal((await labeler.runOnce()).mode,'idle');const events=await labeler.eventPage(first.id);assert.equal(events.length,6);assert.ok(events.every(event=>event.fallback_used&&event.requires_review));
  assert.ok(!JSON.stringify(events).includes('Thử nghiệm'));assert.ok(events.every(event=>!Object.hasOwn(event,'body')&&!Object.hasOwn(event,'state')));
  const local=createKnowledgeBatch(config);const blocked=createAtlasLabeling(db,config,{classify:async docs=>{const result=await local(docs,false);for(const item of result.items)item.reason='jev_auth_failed';return result;}});
  const stop=await blocked.enqueue({limit:1,allow_remote:true});assert.equal((await blocked.runOnce()).reason,'jev_auth_failed');run=await blocked.get(stop.id);assert.equal(run.status,'blocked');assert.equal(run.cursor,'');assert.equal(run.scanned,0);assert.equal((await blocked.eventPage(stop.id)).length,0);
  const recovered=createAtlasLabeling(db,config,{classify:createKnowledgeBatch({...config,jevEnabled:true,jevTransport:'rest'},async(url,options)=>{const request=JSON.parse(options.body);return Response.json({code:0,data:{model:'typesafe-ai/jev',answers:Object.fromEntries(Object.keys(request.questions).map(key=>[key,{type:'choice',choice:'flavor',confidence:0.9,probabilities:{ingredients:0.03,flavor:0.9,safety:0.03,methods:0.02,other:0.02}}]))}});})});
  assert.equal(await recovered.control(stop.id,'resume'),true);await recovered.runOnce();assert.equal((await recovered.get(stop.id)).status,'completed');assert.equal((await recovered.get(stop.id)).jev,1);
  const stale=createAtlasLabeling(db,config,{classify:async docs=>{await db.collection('data_sync_jobs').updateOne({job_key:'knowledge:'+docs[0].resource_id},{$inc:{revision:1}});return local(docs,false);}});
  const outdated=await stale.enqueue({limit:1,allow_remote:false});await stale.runOnce();run=await stale.get(outdated.id);assert.equal(run.stale,1);assert.equal(run.saved,0);assert.equal((await stale.eventPage(outdated.id))[0].outcome,'stale');
  const cancel=createAtlasLabeling(db,config,{classify:async docs=>{await labeler.control(cancelRun.id,'cancel');return local(docs,false);}});
  const cancelRun=await cancel.enqueue({limit:1,allow_remote:false});assert.equal((await cancel.runOnce()).mode,'lease_lost');assert.equal((await cancel.get(cancelRun.id)).status,'cancelled');assert.equal((await cancel.eventPage(cancelRun.id)).length,0);
  const bad=createAtlasLabeling(db,config,{classify:async docs=>{const result=await local(docs,false);result.items[0].confidence=2;return result;}});
  const invalid=await bad.enqueue({limit:1,allow_remote:false});assert.equal((await bad.runOnce()).mode,'stopped');assert.equal((await bad.get(invalid.id)).scanned,0);assert.equal((await bad.eventPage(invalid.id)).length,0);
  await assert.rejects(db.collection('decision_events').insertOne({id:'bad',provider:'grant_admin'}),error=>error.code===121);
  let now=Date.now();const transient=createAtlasLabeling(db,config,{clock:()=>now,classify:async docs=>{const result=await local(docs,false);result.jev_requests=1;for(const item of result.items)item.reason='provider_unavailable';return result;}});
  const retry=await transient.enqueue({limit:1,allow_remote:true});assert.equal((await transient.runOnce()).mode,'retry_scheduled');assert.equal((await transient.runOnce()).mode,'idle');
  now+=30001;assert.equal((await transient.runOnce()).mode,'retry_scheduled');now+=60001;assert.equal((await transient.runOnce()).mode,'stopped');
  run=await transient.get(retry.id);assert.equal(run.status,'failed');assert.equal(run.jev_requests,3);assert.equal(run.scanned,0);assert.equal((await transient.eventPage(retry.id)).length,0);
 }finally{await mirror?.close();if(db.database.databaseName!==name||!/^musuroom_verify_[a-f0-9]{16}$/.test(name))throw Error('Invalid cleanup target');await db.database.dropDatabase();await db.close();}
});
