import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../backend/app.mjs';
import { loadConfig } from '../backend/config.mjs';
import { sensoryMetrics, sensoryCsv } from '../backend/services/sensory-metrics.mjs';
import { createSensoryInterpreter } from '../backend/services/sensory-insights.mjs';
const token = 'sensory-test-token-'.repeat(4);
const score = (value, sample = 'MUSH-01') => ({ session_code: 'ROUND-01', sample_code: sample, tester_type: 'CONSUMER', color_score: value, aroma_score: value, umami_taste_score: value, aftertaste_score: value, overall_acceptance: value });
async function client(t) {
  const server = createApp({ config: loadConfig({ DATABASE_PATH: ':memory:', API_WRITE_TOKEN: token }) });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const call = (path, method = 'GET', body, authorized = false) => fetch(base + path, { method, headers: { ...(body === undefined ? {} : { 'Content-Type': 'application/json' }), ...(authorized ? { Authorization: `Bearer ${token}` } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  return { call, base };
}
test('Hedonic metrics use sample SD, median, distribution and radar in a stable order', () => {
  const rows = [score(1), score(5), score(9)];
  const result = sensoryMetrics(rows, 'ROUND-01', 'MUSH-01');
  assert.equal(result.count, 3);
  assert.equal(result.metrics.color_score.mean, 5);
  assert.equal(result.metrics.color_score.median, 5);
  assert.equal(result.metrics.color_score.sd, 4);
  assert.equal(result.metrics.color_score.distribution[1], 1);
  assert.equal(result.metrics.color_score.distribution[5], 1);
  assert.equal(result.metrics.color_score.distribution[9], 1);
  assert.deepEqual(result.radar.values, [5,5,5,5,5]);
  assert.equal(sensoryMetrics([score(7)], 'R', 'S').metrics.color_score.sd, null);
  assert.equal(sensoryMetrics([], 'R', 'S').metrics.color_score.mean, null);
  assert.equal(sensoryMetrics([score(2), score(9)], 'R', 'S').metrics.color_score.median, 5.5);
});
test('Sensory submission validates every score and separates session/sample; retry key is idempotent', async t => {
  const { call } = await client(t);
  const key = 'a82cf87a-6d5e-4cf2-8b39-552f278bc708';
  const first = score(1);
  first.submission_key = key;
  assert.equal((await call('/api/v1/sensory/submit', 'POST', { ...first, color_score: 0 })).status, 422);
  assert.equal((await call('/api/v1/sensory/submit', 'POST', { ...first, color_score: 1.5 })).status, 422);
  assert.equal((await call('/api/v1/sensory/submit', 'POST', { ...first, aroma_score: '5' })).status, 422);
  assert.equal((await call('/api/v1/sensory/submit', 'POST', { ...first, tester_type: 'JUDGE;DROP' })).status, 422);
  assert.equal((await call('/api/v1/sensory/submit', 'POST', { ...first, sample_code: '../x' })).status, 422);
  assert.equal((await call('/api/v1/sensory/submit', 'POST', { ...first, comments: 99 })).status, 422);
  const created = await call('/api/v1/sensory/submit', 'POST', first);
  assert.equal(created.status, 201);
  const saved = await created.json();
  assert.ok(saved.id); assert.equal(saved.repeated, false);
  const retried = await call('/api/v1/sensory/submit', 'POST', first);
  assert.equal(retried.status, 200);
  assert.equal((await retried.json()).id, saved.id);
  assert.equal((await call('/api/v1/sensory/submit', 'POST', { ...first, aroma_score: 2 })).status, 409);
  await call('/api/v1/sensory/submit', 'POST', score(5));
  await call('/api/v1/sensory/submit', 'POST', score(9));
  await call('/api/v1/sensory/submit', 'POST', score(9, 'MUSH-02'));
  const path = '/api/v1/sensory/analytics?session_code=ROUND-01&sample_code=MUSH-01';
  assert.equal((await call(path)).status, 401);
  const analytics = await (await call(path, 'GET', undefined, true)).json();
  assert.equal(analytics.count, 3);
  assert.equal(analytics.metrics.overall_acceptance.mean, 5);
  assert.equal(analytics.metrics.overall_acceptance.sd, 4);
  assert.equal((await (await call('/api/v1/sensory/analytics?session_code=ROUND-01&sample_code=MUSH-02', 'GET', undefined, true)).json()).count, 1);
  assert.equal((await call('/api/v1/sensory/analytics', 'GET', undefined, true)).status, 400);
  const interpreted = await (await call('/api/v1/sensory/insights', 'POST', { session_code: 'ROUND-01', sample_code: 'MUSH-01' }, true)).json();
  assert.equal(interpreted.mode, 'descriptive');
  assert.equal(interpreted.basis.count, 3);
  assert.equal(interpreted.reason, 'ai_disabled');
});
test('Optional sensory AI receives aggregates only and falls back on unsupported output', async () => {
  const metrics = sensoryMetrics([score(2), score(5), score(8)], 'ROUND-01', 'MUSH-01');
  const config = loadConfig({ DATABASE_PATH: ':memory:', AI_PROVIDER: 'openrouter', OPENROUTER_API_KEY: 'mock-key', AI_MODEL: 'mock/model' });
  let prompt;
  const ai = createSensoryInterpreter(config, async (url, options) => {
    prompt = JSON.parse(options.body).messages[1].content;
    return { ok: true, json: async () => ({ choices: [{ message: { content: 'Các điểm trung bình khá cân bằng giữa các tiêu chí.' } }] }) };
  });
  const result = await ai(metrics);
  assert.equal(result.mode, 'ai');
  assert.ok(!prompt.includes('comments'));
  assert.ok(!prompt.includes('phone_or_email'));
  assert.ok(!prompt.includes('mock-key'));
  const invalid = await createSensoryInterpreter(config, async () => ({ ok: true, json: async () => ({ choices: [{ message: { content: 'Đạt 99 điểm.' } }] }) }))(metrics);
  assert.equal(invalid.mode, 'descriptive');
  assert.equal(invalid.reason, 'invalid_response');
  assert.equal((await ai(sensoryMetrics([score(7)], 'R', 'S'))).reason, 'too_few_responses');
});
test('Sensory CSV is protected, scoped and escapes spreadsheet formulas', async t => {
  const { call } = await client(t);
  const input = { ...score(7), comments: '=HYPERLINK("https://example.test","click")' };
  await call('/api/v1/sensory/submit', 'POST', input);
  const body = { session_code: 'ROUND-01', sample_code: 'MUSH-01' };
  assert.equal((await call('/api/v1/sensory/export', 'POST', body)).status, 401);
  const response = await call('/api/v1/sensory/export', 'POST', body, true);
  assert.equal(response.status, 200);
  const csv = Buffer.from(await response.arrayBuffer()).toString('utf8');
  assert.ok(csv.startsWith('\uFEFF'));
  assert.ok(csv.includes("'=HYPERLINK"));
  assert.ok(csv.includes('ROUND-01'));
  assert.equal((await call('/api/v1/sensory/export', 'POST', { session_code: '../../bad', sample_code: 'MUSH-01' }, true)).status, 422);
  assert.ok(sensoryCsv([{ id: 'x', comments: '+SUM(1,2)' }]).includes("'+SUM"));
});
test('Sample registration requires consent, normalizes contact, and admin data needs token', async t => {
  const { call } = await client(t);
  const lead = { full_name: '  An  Nguyen  ', phone_or_email: 'An@example.com', organization_type: 'INDIVIDUAL', dietary_preference: 'VEGAN', consent: true };
  assert.equal((await call('/api/v1/leads/register', 'POST', { ...lead, consent: false })).status, 422);
  assert.equal((await call('/api/v1/leads/register', 'POST', { ...lead, phone_or_email: 'bad' })).status, 422);
  assert.equal((await call('/api/v1/leads/register', 'POST', { ...lead, organization_type: 'INVALID' })).status, 422);
  const created = await call('/api/v1/leads/register', 'POST', lead);
  assert.equal(created.status, 201);
  const registered = await created.json();
  assert.ok(registered.id); assert.equal(registered.status, 'PENDING');
  assert.ok(!JSON.stringify(registered).includes('An@example.com'));
  const repeated = await call('/api/v1/leads/register', 'POST', { ...lead, phone_or_email: 'an@EXAMPLE.COM' });
  assert.equal(repeated.status, 200); assert.equal((await repeated.json()).id, registered.id);
  assert.equal((await call('/api/v1/admin/leads')).status, 401);
  const list = await (await call('/api/v1/admin/leads?status=PENDING', 'GET', undefined, true)).json();
  assert.equal(list.items.length, 1); assert.equal(list.items[0].full_name, 'An Nguyen');
  assert.equal((await call('/api/v1/admin/leads?status=INVALID', 'GET', undefined, true)).status, 400);
  const status = await call(`/api/v1/admin/leads/${registered.id}`, 'PATCH', { status: 'SENT' }, true);
  assert.equal(status.status, 200);
  assert.equal((await status.json()).status, 'SENT');
  assert.equal((await call(`/api/v1/admin/leads/${registered.id}`, 'DELETE')).status, 401);
  assert.equal((await call(`/api/v1/admin/leads/${registered.id}`, 'DELETE', undefined, true)).status, 204);
  assert.equal((await (await call('/api/v1/admin/leads', 'GET', undefined, true)).json()).items.length, 0);
});
